CREATE TABLE "FileTag" ( 
	"id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	"TagId" INTEGER NOT NULL , 
	"FileId" VARCHAR(36), 
	`createdAt` DATETIME NOT NULL, 
	`updatedAt` DATETIME NOT NULL, 
	FOREIGN KEY (TagId) REFERENCES Tag(id), 
	FOREIGN KEY (FileId) REFERENCES Files(id) 
	)